### ISSUE TITLE
ASX data webservice has moved

### ISSUE THREAD

**Issue by zacscott** [geeknam/asx-terminus#2]
It looks like the ASX data.asx.com.au webservice has been moved. To get the share price I had to change the endpoint to `"http://data.asx.com.au/data/1/share/%s/"`

**Comment by zacscott** [comment]
I've set up a PR to change the endpoint. I realised after I had already done that you've changed it use AlphaVantage in the `develop` branch, so can just close this issue I guess. I'll give the `develop` branch version a go and see if it works for me.

**Comment by geeknam** [comment]
Yeah, I'm leaning towards AlphaVantage, don't want unexpected changes from ASX API again. Thanks anyway.
